### ISSUE TITLE
Bloom effect is not expected

### ISSUE THREAD

**Issue by thigiacmay** [Tape-Worm/Gorgon#15]
I asked this question in GameDev. My goal is to apply Bloom effect on Red border of texture. I changed the Format as you said from R8G8B8A8_UNorm to R16G16B16A16_UNorm but i got unexpected result. Please have a look on my codes. Thanks:

```
private static Gorgon2DBloomEffect _bloomEffect;
private static GorgonTexture2DView _bloomTextur2DView;
private static GorgonRenderTarget2DView _bloomRenderTargetView2D;
		
//Init bloom effect
_bloomEffect = new Gorgon2DBloomEffect(_renderer)
{
	Threshold = 8.11f,
	BloomIntensity = 6.0f,
	BlurAmount = 60.3f,
	ColorIntensity = 10.15f,
	Color = new GorgonColor(0.8f, 0.0f, 0.0f, 1f)
};	
//Init texture, ..
GorgonCodecPng png = new GorgonCodecPng();
var CardImage = png.LoadFromFile(@"D:\\1281720.png");

_bloomTextur2DView = GorgonTexture2DView.CreateTexture(_graphics,
					  new GorgonTexture2DInfo("Shadow Texture")
					  {
						  Width = (int)CardImage.Width,
						  Height = (int)CardImage.Height,
						  Binding = TextureBinding.RenderTarget | TextureBinding.ShaderResource,
						  Usage = ResourceUsage.Default,
						  Format = BufferFormat.R16G16B16A16_UNorm
					  }, CardImage);

_bloomTextur2DView.OwnsResource = true;
_bloomRenderTargetView2D = _bloomTextur2DView.GetRenderTargetView();

//In Idle func
_graphics.SetRenderTarget(_bloomRenderTargetView2D);
         
_bloomEffect.Render((_, __, size) =>
			{
				_renderer.DrawFilledRectangle(new SharpDX.RectangleF(0, 0, _bloomTextur2DView.Width, _bloomTextur2DView.Height), GorgonColor.White, _bloomTextur2DView, new SharpDX.RectangleF(0, 0, 1, 1));
			}, _bloomRenderTargetView2D);

_graphics.SetRenderTarget(_screen.RenderTargetView);
_renderer.Begin();
int x = 20, y = 1080 - _bloomTextur2DView.Height - 40, delta_x = _bloomTextur2DView.Width + 20;
_renderer.Dra﻿wFilledRectangle(new SharpDX.RectangleF(x, y, _bloomTextur2DView.Width, _bloomTextur2DView.Height), GorgonColor.White, _bloomTextur2DView, new SharpDX.RectangleF(0f, 0f, 1f, 1f));
_renderer.End();
```

This is texture image: 
![Texture](https://user-images.githubusercontent.com/26891185/64103678-f4f80d00-cd9c-11e9-9ef7-95a528c06e16.png)
And result of bloom effect:
![NO BLOOM](https://user-images.githubusercontent.com/26891185/64112509-d94b3180-cdb1-11e9-9927-e385e8610877.png)

**Comment by Tape-Worm** [comment]
There are several problems with how you're doing this that make the effect break down.

1. You're loading your card image into the render target directly.  The effect (like most effects) requires that you actually draw something into the render target.  The way to fix this is to load the card image into a separate texture like so: 
![image](https://user-images.githubusercontent.com/9710137/64126381-b9444f80-cd6a-11e9-958f-5833245e7b22.png)
Remove the image loading function (CardImage = Png.FromFile....), you don't need this.
2. Your bloom settings are not going to work.  You need to lower your threshold and decrease your blur amount:
![image](https://user-images.githubusercontent.com/9710137/64126439-f6a8dd00-cd6a-11e9-80a4-bda93ddd1784.png)
Ultimately, you'll need to play with the settings to get the image you want.
3. In your idle function, instead of rendering the bloomRenderTargetView inside of the Render method, render your card like so:
![image](https://user-images.githubusercontent.com/9710137/64126526-4b4c5800-cd6b-11e9-8bdc-8d6c075f56c1.png)
4. Finally, when rendering the effect overlay, you need to use Additive blending:
![image](https://user-images.githubusercontent.com/9710137/64126540-65863600-cd6b-11e9-8205-3005adc5a0b3.png)

All of that will yield this image as a result (your background image will be different than mine obviously):
![image](https://user-images.githubusercontent.com/9710137/64126573-8b133f80-cd6b-11e9-9042-17e5c71c7fe5.png)

In case there's anything I've missed, I've attached the code I used to create the bloom effect:
[Issue_15.zip](https://github.com/Tape-Worm/Gorgon/files/3566687/Issue_15.zip)

Now, with all that said, this is an incredibly expensive operation just to render a single image with a bit of glow... I wouldn't be using bloom to do this, I'd alter the card image in Photoshop (or paint.net, gimp, etc...) to have a blur, and then draw it with additive blending.  That should give you a very similar look with way better performance. Even with a video in the background (unless you're blooming the video too), this approach would be much, much better.

**Comment by thigiacmay** [comment]
I dont know why it is _screen.Width and _screen.Height in this code?
```

_bloomTextur2DView = NhatQuangMvtecTexture2DView.CreateTexture(_graphics,
                                  new NhatQuangMvtecTexture2DInfo("Shadow Texture")
                                  {
                                      Width = (int)_screen.Width,
                                      Height = (int)_screen.Height,
                                      Binding = TextureBinding.RenderTarget | TextureBinding.ShaderResource,
                                      Usage = ResourceUsage.Default,
                                      Format = BufferFormat.R16G16B16A16_UNorm
                                  });
```
Why it is not _card.Wdith and _card.Height ?

**Comment by Tape-Worm** [comment]
Because Bloom, like many effects, is a post processing effect meant to work on the full screen.

If you look up [Bloom/Glow effects online](https://learnopengl.com/Advanced-Lighting/Bloom), you'll see that every one of them uses the effect as a post processing effect on the full screen. It basically reads render target and filters for the brightest objects on the screen, then blurs it using additive blending.  

Aside from that, you can use a smaller render target if you wish, but you may run into issues.

If you want bloomed sprites, you should render the sprites that you want bloomed in the Render() method of the effect.

Again, Bloom is not really a good method for just making sprites glow. It's really meant to enhance lighting for a scene. And, as I said, it's incredibly expensive to render.  Using blurred images and additive blending is much more efficient and you can use them directly as sprites should you require that.

**Comment by thigiacmay** [comment]
Yes, Thank you, i will learn more about Bloom and Blur from your Api and will ask you more 👍 
One more question before you close this:
Is there any function in Gorgon that can convert GoronImage from BufferFormat.R8G8B8A8_UNorm to BufferFormat.R16G16B16A16_UNorm? Because cause I have RGB24 image from camera i captured, i have converted it to BufferFormat.R8G8B8A8_UNorm, now i want to convert it BufferFormat.R16G16B16A16_UNorm.

**Comment by Tape-Worm** [comment]
I don't really know.  Gorgon uses [WIC](https://docs.microsoft.com/en-us/windows/win32/wic/-wic-about-windows-imaging-codec) underneath the hood to do image conversion, so if it supports it, then Gorgon will too.  The IGorgonImage object has a CanConvert function that will let you know if it can convert the format.

That said, you shouldn't be converting your images to 16 bit per channel, there's no real advantage to doing that.  16 bit per channel is mainly used for HDR rendering (typically for render targets), and it's quite wasteful to load all of your textures in that format as you get no perceptual difference in color depth as your monitor, most likely, is going to only output 8 bit per channel.

**Comment by Tape-Worm** [comment]
So, just to show you what I mean by using a blurred texture and additive blending:
![image](https://user-images.githubusercontent.com/9710137/64134574-523f8e80-cd9c-11e9-937f-cedf689bcbe5.png)

All I did was blur the image sufficiently in Photoshop (However, I went too far with it, the square edges on the glow are my fault entirely - nothing to do with Gorgon). And then, instead of using bloom, I rendered the blurred image on top of my background and I also rendered the card image below the glow using default blending.

This will perform WAY better than the Bloom effect and, at this point, looks better - except for my screw up with the texture. It just requires that you do some image manipulation.

Here's the code I used to generate the image:
[Issue_15_Glow.zip](https://github.com/Tape-Worm/Gorgon/files/3567156/Issue_15_Glow.zip)

**Comment by dominota** [comment]
Bloom effect with AdditiveBlend makes whole the card bloomed while i only want bloom the red border of card (event i SetData for card)
![bloom](https://user-images.githubusercontent.com/54459455/64141198-5c5f9c80-ce31-11e9-94e7-78385434e11c.png)

**Comment by Tape-Worm** [comment]
It's not really easy to control at that level.  Again, Bloom (I mean the effect in general, this is not specific to Gorgon, Unity, for example, handles it in the same way) is meant for lighting, so it handles bright areas on the screen, and it doesn't do any kind of color matching.

If you follow the suggestion for blurred textures + additive, you can control the glow for whatever colors however you want in whatever paint program you like.

**Comment by Tape-Worm** [comment]
I manipulated the card image in Photoshop to have a better looking glow:
![image](https://user-images.githubusercontent.com/9710137/64145252-37d5d700-cdd5-11e9-8d05-49932ab7fe92.png)

I isolated the red border easily using the magic wand tool on the purple inside, and cutting the body out and putting it on another layer, then blurring the border layer in Photoshop (you could do this in Paint.NET or Gimp as well).  

Here's the glowing border I used:
![card_glow](https://user-images.githubusercontent.com/9710137/64145263-3efce500-cdd5-11e9-91a6-2cda85de5011.png)

**Comment by dominota** [comment]
> 
> 
> I manipulated the card image in Photoshop to have a better looking glow:
> ![image](https://user-images.githubusercontent.com/9710137/64145252-37d5d700-cdd5-11e9-8d05-49932ab7fe92.png)
> 
> I isolated the red border easily using the magic wand tool on the purple inside, and cutting the body out and putting it on another layer, then blurring the border layer in Photoshop (you could do this in Paint.NET or Gimp as well).
> 
> Here's the glowing border I used:
> ![card_glow](https://user-images.githubusercontent.com/9710137/64145263-3efce500-cdd5-11e9-91a6-2cda85de5011.png)

Yes yes yes, that is what i expected with Bloom. But i will do with blur like you suggested. 

I need card_glow.png file with size 1340x780 and rounded corners with this params, I created this template card like this (but i can not blur it)

var Card_Background = new D2D.SolidColorBrush(Graphics.D2D1Context5, new var SharpDX.Mathematics.Interop.RawColor4(0.6f, 0.5f, 0.6f, 0.7f));
var Card_Border = new D2D.SolidColorBrush(Graphics.D2D1Context5, new SharpDX.Mathematics.Interop.RawColor4(1.0f, 00f, 0f, 1f));
Size2 Card_Size_Main = new Size2(1340,780)
int RadiusX = 50, RadiusY = 50;
int Card_Border= 4;
int inner_offset = 10;
var Card_Bitmap = new D2D.Bitmap1(Graphics.D2D1Context5, Card_Size_Main, new D2D.BitmapProperties1()
            {
                PixelFormat = new D2D.PixelFormat(SharpDX.DXGI.Format.R8G8B8A8_UNorm, D2D.AlphaMode.Premultiplied),
                DpiX = 96,
                DpiY = 96,
                BitmapOptions = D2D.BitmapOptions.Target
            });
 Graphics.D2D1Context5.Target = Card_Bitmap;
Graphics.D2D1Context5.BeginDraw();
Graphics.D2D1Context5.FillRoundedRectangle(new D2D.RoundedRectangle() { RadiusX = 50, RadiusY = 50, Rect = new SharpDX.Mathematics.Interop.RawRectangleF(inner_offset , inner_offset , Card_Size_Main.Width - inner_offset , Card_Size_Main.Height - inner_offset ) }, Card_Background);
Graphics.D2D1Context5.DrawRoundedRectangle(new D2D.RoundedRectangle() { RadiusX = 50, RadiusY = 50, Rect = new SharpDX.Mathematics.Interop.RawRectangleF(inner_offset , inner_offset , Card_Size_Main.Width - inner_offset , Card_Size_Main.Height - inner_offset ) }, Card_Border, 4, new D2D.StrokeStyle(Graphics.D2D1Context5.Factory, new D2D.StrokeStyleProperties() { DashStyle = D2D.DashStyle.Dash }));
Graphics.D2D1Context5.EndDraw();

Can you adjust your PSD and share with me the card_glow.png again? (it would be nice with your psd file too). 

Thanks :))

**Comment by Tape-Worm** [comment]
I don't have the PSD file, and I'm not an artist.  Just download Paint.NET or Gimp and play around with it until you get the result you want.

**Comment by dominota** [comment]
Thank you so much! Please close this thread
