### ISSUE TITLE
Error when calling GorgonGraphics.EnumerateAdapters

### ISSUE THREAD

**Issue by Ranarrr** [Tape-Worm/Gorgon#20]
GorgonException: There was an error during creation.
The Gorgon Graphics interface requires Windows 10 (Build 15603) or better.

Looking at example "Balls", trying to convert to VB.NET, then I get runtime error.

Expected the function to go through without a hitch, as I'm currently running Microsoft Windows [Version 10.0.17763.1039].
![screenshot 8](https://user-images.githubusercontent.com/7990338/74786476-1a29fa80-52ad-11ea-8f4d-16e3b0d00a7f.jpg)

Thank you for your work.

**Comment by Tape-Worm** [comment]
I'm guessing that no other examples work either?

I'm looking through the O/S detection code now to see if there's something not set up correctly.

**Comment by Tape-Worm** [comment]
OK, so I think I know what your issue is.  You need to add an app.manifest to your application so that it can properly detect Windows 10. This is required for all apps (including C++).  This is from the MSDN documentation on the function used to [verify the version #](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-verifyversioninfoa):

> "Windows 10:  VerifyVersionInfo returns false when called by applications that do not have a compatibility manifest for Windows 8.1 or Windows 10 if the lpVersionInfo parameter is set so that it specifies Windows 8.1 or Windows 10, even when the current operating system version is Windows 8.1 or Windows 10."

If you read this link from the documentation: [https://www.tape-worm.net/GorgonDocs/html/564985CC-F18F-4711-A2BC-0796D266E54D.htm](https://www.tape-worm.net/GorgonDocs/html/564985CC-F18F-4711-A2BC-0796D266E54D.htm)

It'll explain what you need to do, this should apply to VB.Net as well.

**Comment by Tape-Worm** [comment]
By the way, I was just looking at your code in the screen shot, and that line where you're throwing an exception will probably not do what you think it will.  Windows Form events like Form_Load tend to just eat the exception.  My suggestion is that you catch any errors, display a message dialog, and then exit using a try-catch block in the Form_Load event. 

See [https://stackoverflow.com/questions/3209706/why-the-form-load-cant-catch-exception](https://stackoverflow.com/questions/3209706/why-the-form-load-cant-catch-exception)

**Comment by Ranarrr** [comment]
Wow! Thank you for the quick AND thorough response. I've never done any graphics handling, or using D3D for that matter, so this wasn't something that popped up in my mind. I will also be taking your advice and using try catch in my code (for Load event). My bad for not reading the documentation very thoroughly (will do before I try to post any other "bugs").
Gotta say again, thank you very much for your response :)
