### ISSUE TITLE
Overload LoadTrueTypeFontFamily

### ISSUE THREAD

**Issue by Ranarrr** [Tape-Worm/Gorgon#23]
**Is your feature request related to a problem? Please describe.**
I am unable to load a font from memory (embedded resource).

**Describe the solution you'd like**
Overload LoadTrueTypeFontFamily with the possibility of using font from memory.

**Describe alternatives you've considered**
I don't see another way. If this is not the case, please let me know how I would be able to load a font from memory (as an embedded resource)

**Comment by Tape-Worm** [comment]
Unfortunately, the underlying font functionality provided by .NET doesn't allow for loading from an array, or from a stream. This is why there's no method to load the font arbitrarily.

I'll give it some thought and see if I can't devise something to work around this. But it could take a while. 

In the meantime, you can take your font resource (which should be a resource of byte[]), and save it to a temporary file, and load the font from that file and delete the temp file when done.

**Comment by Ranarrr** [comment]
PrivateFontCollection has a method "AddMemoryFont", is this method not usable for this purpose?
Please see this code (it's in VB though..)
`Dim fontMem As IntPtr = Marshal.AllocCoTaskMem(My.Resources.my_font.Length)
Marshal.Copy(My.Resources.my_font, 0, fontMem, My.Resources.my_font.Length)
Dim tmpfont As New PrivateFontCollection
tmpfont.AddMemoryFont(fontMem, My.Resources.my_font.Length)`

**Comment by Tape-Worm** [comment]
It does, but it relies on native memory. I won't add functionality that requires people to allocate native memory in order to use said functionality. That defeats one of the key reasons to use .NET.

For example, you've got that code there, and you've allocated a native memory block with AllocCoTaskMem.  When are you going to free that?  The garbage collector won't do it for you, and if you forget to do it, you'd have a memory leak. There's a whole host of issues with native memory management if we're not very careful.

Again, I would just send the font to disk, read it in, then delete the file for now. There's a way to get around the native memory thing, I just need time, which I lack right now, to write it and test it.

**Comment by Ranarrr** [comment]
I will do what you suggest, thank you and I will be patient and wait until you have time :)

**Comment by Tape-Worm** [comment]
Version 3.0.96.088 is now available. You should be able to load your font from a stream (look at the font example application to see how to use this with your resource).

**Comment by Ranarrr** [comment]
Can give a positive feedback, it works perfectly, thank you :D
