### ISSUE TITLE
Question regarding Direct3D 11.4

### ISSUE THREAD

**Issue by Ranarrr** [Tape-Worm/Gorgon#25]
I am unable to find a lot of information on "Direct3D 11.4", I was hoping you could answer.

Q1: Which feature set is required for this version of D3D?

Q2: Will Gorgon be compatible with earlier versions of D3D in the future (require lower level feature sets)? The reason I ask this is because a number of people (around 10 at the moment), that is playing a game I created using Gorgon, is complaining that my game doesn't support older GPU's which should be able to handle a relatively simple 2D game.

Thanks :)

**Comment by Tape-Worm** [comment]
For future reference, questions like this are not considered bugs.  Please don't tag them as such. If you're unsure, then leave it to me to tag.

1. Gorgon uses Direct 3D 11.4 - Which means it requires a video card that supports Direct 3D 12 at minimum. This is in the [documentation](https://www.tape-worm.net/GorgonDocs/index.html), on the bottom of the very first page.

2. I will look into it. I know that Gorgon uses very few features from the extended feature levels. It's entirely possible that it doesn't use anything from 11.3 or 11.4 (I need to go back through the code to determine if this is the case).  If I find that it doesn't use 11.3/11.4 features (I know it uses 11.2 features for certain), then I can drop the required feature level down.  _However_, if it does use features from 11.3/11.4, then I won't be changing it as it'd be a major pain to make it compliant with multiple feature levels.

Keep in mind, that this will not be a trivial thing, so this will have to wait until 3.1 is released (looking at July/August for that).

I'll keep this open until I can get back to you with the results of my findings.

**Comment by Tape-Worm** [comment]
Work has begun on this item.  Will update with my findings.

**Comment by Tape-Worm** [comment]
So it looks like everything's fine in D3D 11.2.

I've updated the 3.1 branch to include this fix. You may pull that branch down and compile it and give it a shot. Be aware that 3.1 is:

- Not done yet.
- Likely to have bugs.
- Definitely has breaking changes - so you'll need to modify your code most likely.

**Comment by Ranarrr** [comment]
As for converting the code; I had to include a name as a parameter to Edit2DTexture. However when I just included a random name, all the animations were just white squares. I later figured out for the name parameter I'd have to pass "Texture" as name, as to edit the texture of the GorgonTexture2DView. It didn't come across clear enough for me that the redesigned Animation API included Edit2DTexture, but now I know.

I'll come back later with tests done with users that had problems. So far it's working perfectly for me atleast.

Cheers

**Comment by Tape-Worm** [comment]
Yes, you need a name for the track registration so the animation system can correlate the key frames to the correct properties on the animated object. The fault is mine because the animation system is poorly documented at the moment (and thank you for mentioning this, I'll make a note to try and clean that up).

As you've learned, you should not pass in an arbitrary name, this name is for the registration of the track. For the sprite animation controller, you can get the registration easily by using the static values present on that class.  So for example, you can do this:
`Edit2DTexture(GorgonSpriteAnimationController.TextureTrack.TrackName)`

or for sprite rotation you can do:
`EditSingle(GorgonSpriteAnimationController.AngleTrack.TrackName)`

And so on...

Each of the included controllers have their track registrations exposed as static variables that you can interrogate and get metadata from. And the controllers have a property called RegisteredTracks as well that you can interrogate after creating an instance of the controller.

Hope that clears things up.

**Comment by Tape-Worm** [comment]
Since this seems to be resolved, I'm going to close this issue.
