### ISSUE TITLE
Gorgon 2.0 artefacts

### ISSUE THREAD

**Issue by stigzler** [Tape-Worm/Gorgon#5]
Hello fella,

Firstly - thank you so much for this! I've been scouring the net for weeks trying to find a .net accessible 2D drawing library and I'm hoping I've finally found it! As per:

[https://www.gamedev.net/forums/topic/699147-recommend-a-simple-net-2d-library/?tab=comments#comment-5391882](https://www.gamedev.net/forums/topic/699147-recommend-a-simple-net-2d-library/?tab=comments#comment-5391882)

It's looking like meeting the broadest of requirements - text, image and geometry rendering. It's looking like it won't do videos, however?

Either way - it's a great project. However, I am getting some artefacts on text rendering. Video:

[https://youtu.be/yYSFY5NNllo](https://youtu.be/yYSFY5NNllo)

Code:

[https://pastebin.com/iaYXkJFW](https://pastebin.com/iaYXkJFW)

Hope you can help!

(p.s. I did try downloading 3, but got lost compiling the dll - got all sorts or errors - nothing to do with your code, more my setup)

**Comment by Tape-Worm** [comment]
My first instinct is that it might be artifacts due to the bilinear filtering.  

First thing to try is to turn off the smoothing and see if the artifacts disappear (it'll look blocky though).  If that removes the artifacts, then you'll need to introduce padding between the glyphs when generating the font.  This should correspond to the GlyphLeftOffset, GlyphTopOffset, GlyphWidthOffset and GlyphHeightOffset properties on the font.

As for video, no, there's no built-in video support unfortunately.

**Comment by stigzler** [comment]
Thanks for the reply. Removing smoothing made no difference. :(
